export const banks = [
  {
    id: 1,
    name: "Access Bank",
    description:
      "Access Bank is a multinational commercial bank in Nigeria and a major player in the financial industry.",
    href: "/bandetails/access-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 2,
    name: "Agricultural Development Bank (ADB)",
    description:
      "ADB is a state-owned development and commercial bank in Ghana, contributing to the agricultural sector's growth.",
    href: "/bandetails/agricultural-development-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 3,
    name: "Bank of Africa",
    description:
      "Bank of Africa is a pan-African banking group with a presence in multiple countries, providing financial services.",
    href: "/bandetails/bank-of-africa",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 4,
    name: "Barclays Bank (now Absa Bank)",
    description:
      "Barclays Bank, now Absa Bank, is a major financial institution with a global presence, offering diverse financial services.",
    href: "/bandetails/absa-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 5,
    name: "CalBank",
    description:
      "CalBank is a leading commercial bank in Ghana, committed to providing innovative banking solutions and services.",
    href: "/bandetails/calbank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 6,
    name: "Consolidated Bank Ghana (CBG)",
    description:
      "CBG is a result of the merger of some Ghanaian banks, offering a wide range of financial products and services.",
    href: "/bandetails/consolidated-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 7,
    name: "Ecobank Ghana",
    description:
      "Ecobank Ghana is a subsidiary of the Ecobank Group, providing a comprehensive range of financial services across Africa.",
    href: "/bandetails/ecobank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 8,
    name: "Fidelity Bank",
    description:
      "Fidelity Bank is a leading Ghanaian bank, committed to delivering innovative banking solutions and excellent customer service.",
    href: "/bandetails/fidelity-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 9,
    name: "First Atlantic Bank",
    description:
      "First Atlantic Bank is a full-service commercial bank in Ghana, providing a wide range of financial products and services.",
    href: "/bandetails/first-atlantic-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 10,
    name: "First National Bank",
    description:
      "First National Bank (FNB) is a prominent financial institution, offering a variety of banking and financial services.",
    href: "/bandetails/first-national-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 11,
    name: "FNB Bank",
    description:
      "FNB Bank is committed to providing innovative banking solutions and excellent customer service, contributing to financial growth.",
    href: "/bandetails/fnb-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 12,
    name: "GCB Bank",
    description:
      "GCB Bank is a leading bank in Ghana, offering a comprehensive range of financial products and services to individuals and businesses.",
    href: "/bandetails/gcb-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 13,
    name: "GN Bank",
    description:
      "GN Bank is dedicated to providing financial solutions, focusing on customer satisfaction and contributing to economic development.",
    href: "/bandetails/gn-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 14,
    name: "Republic Bank Ghana",
    description:
      "Republic Bank Ghana is part of the Republic Financial Holdings Limited, offering a range of financial services and solutions.",
    href: "/bandetails/republic-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 15,
    name: "Societe Generale Ghana",
    description:
      "Societe Generale Ghana is a subsidiary of Societe Generale Group, providing a wide range of banking and financial services.",
    href: "/bandetails/societe-generale-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 16,
    name: "Standard Chartered Bank Ghana",
    description:
      "Standard Chartered Bank Ghana is a leading international bank, providing a broad range of financial services to individuals and businesses.",
    href: "/bandetails/standard-chartered-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 17,
    name: "Stanbic Bank Ghana",
    description:
      "Stanbic Bank Ghana is part of the Standard Bank Group, offering a comprehensive suite of financial products and services.",
    href: "/bandetails/stanbic-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 18,
    name: "UMB Bank",
    description:
      "UMB Bank is a Ghanaian bank committed to providing excellent financial services and contributing to the economic growth of the nation.",
    href: "/bandetails/umb-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 19,
    name: "UniBank Ghana",
    description:
      "UniBank Ghana, now part of Consolidated Bank Ghana, was a leading bank offering a wide range of financial solutions.",
    href: "/bandetails/unibank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 20,
    name: "Zenith Bank Ghana",
    description:
      "Zenith Bank Ghana is a subsidiary of Zenith Bank Plc, providing innovative financial solutions to individuals and businesses.",
    href: "/bandetails/zenith-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 21,
    name: "Universal Merchant Bank",
    href: "/bandetails/universal-merchant-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Universal Merchant Bank is a leading financial institution committed to providing innovative banking solutions.",
  },
  {
    id: 22,
    name: "Prudential Bank",
    href: "/bandetails/prudential-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Prudential Bank is dedicated to delivering reliable financial services with a focus on customer satisfaction and integrity.",
  },
  {
    id: 23,
    name: "Stanbic Bank",
    href: "/bandetails/stanbic-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Stanbic Bank is a leading financial institution with a global presence, offering comprehensive banking solutions for businesses and individuals.",
  },
  {
    id: 24,
    name: "Standard Chartered Bank",
    href: "/bandetails/standard-chartered-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Standard Chartered Bank is a renowned international bank, providing a wide range of financial services and solutions.",
  },
  {
    id: 25,
    name: "Sterling Bank",
    href: "/bandetails/sterling-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Sterling Bank is committed to delivering top-notch banking services, ensuring customer satisfaction and financial excellence.",
  },
  {
    id: 26,
    name: "United Bank for Africa (UBA)",
    href: "/bandetails/uba-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "United Bank for Africa (UBA) is a leading pan-African bank, providing innovative financial solutions across the continent.",
  },
  {
    id: 27,
    name: "Zenith Bank",
    href: "/bandetails/zenith-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
    description:
      "Zenith Bank is a prominent financial institution committed to excellence, providing a wide range of banking and financial services.",
  },
];
