export const investmentBanks = [
  {
    id: 1,
    name: "Investment Bank Ghana",
    href: "/ib-details/investment-bank-ghana",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 2,
    name: "Capital Market Advisors",
    href: "/ib-details/capital-market-advisors",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 3,
    name: "Prestige Investments",
    href: "/ib-details/prestige-investments",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 4,
    name: "Global Finance Partners",
    href: "/ib-details/global-finance-partners",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 5,
    name: "Sovereign Investment Bank",
    href: "/ib-details/sovereign-investment-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 6,
    name: "Strategic Wealth Advisors",
    href: "/ib-details/strategic-wealth-advisors",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 7,
    name: "Secure Investments Limited",
    href: "/ib-details/secure-investments-limited",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 8,
    name: "Beacon Capital Investments",
    href: "/ib-details/beacon-capital-investments",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 9,
    name: "Visionary Capital Partners",
    href: "/ib-details/visionary-capital-partners",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 10,
    name: "Frontier Finance Corporation",
    href: "/ib-details/frontier-finance-corporation",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 11,
    name: "Liberty Investment Bank",
    href: "/ib-details/liberty-investment-bank",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 12,
    name: "Quantum Capital Advisors",
    href: "/ib-details/quantum-capital-advisors",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 13,
    name: "Noble Finance Group",
    href: "/ib-details/noble-finance-group",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 14,
    name: "Harmony Capital Management",
    href: "/ib-details/harmony-capital-management",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 15,
    name: "Elite Investment Partners",
    href: "/ib-details/elite-investment-partners",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 16,
    name: "Gold Coast Capital Holdings",
    href: "/ib-details/gold-coast-capital-holdings",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 17,
    name: "Apex Financial Services",
    href: "/ib-details/apex-financial-services",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 18,
    name: "Starlight Investment Solutions",
    href: "/ib-details/starlight-investment-solutions",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 19,
    name: "Summit Securities Limited",
    href: "/ib-details/summit-securities-limited",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
  {
    id: 20,
    name: "Premier Capital Ventures",
    href: "/ib-details/premier-capital-ventures",
    status: "active",
    createdBy: "Courtney Henry",
    updatedFrom: "June 10, 2023",
    updatedTo: "2023-06-10T00:00Z",
  },
];
